version: "3"

services:
  postgres:
    image: "postgres:14.4-alpine3.16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vejce
    ports:
      - "5432:5432"
    volumes:
      - "./bin/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh"

  api:
    image: node:18.7.0-alpine3.16
    environment:
      PG_HOST: postgres
      API_HOST: "0.0.0.0"
    command: [sh, -c, "yarn && yarn scrape && yarn api"]
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - "./:/app"
      - "modules_api:/app/node_modules"
      - "yarn_cache_api:/app/.yarn/cache"

  app:
    image: node:18.7.0-alpine3.16
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    working_dir: /app
    command: [sh, -c, "yarn && yarn dev --host"]
    volumes:
      - "./:/app"
      - "modules_app:/app/node_modules"
      - "cache_app:/app/estates/node_modules"
      - "yarn_cache_app:/app/.yarn/cache"

  adminer:
    image: adminer
    ports:
      - "9000:8080"

volumes:
  modules_api:
  yarn_cache_api:
  modules_app:
  cache_app:
  yarn_cache_app:
